### PR TITLE
Turned Statistic into a header-only class template

### PR DESCRIPTION
**Pull request by glencornell**
### Added

- CHANGELOG.md: moved history in Statistic.cpp to this file.

### Changed

- Turned this into a header-only library to make use of compiler
  inline optimizations.

- Turned this into a class template to reduce dead code at compile
  time and allow for the use of other floating point formats (double,
  long double for example).

### Fixed

- Replaced `#include <Arduino.h>` with `#include <cstdint>` to find
  the proper location of `uint32_t`.  This also allows one to use the
  library in non-Arduino environments.

### CODE REVIEW

**Comment by RobTillaart** [comment]
Thanks for this PR, will review it this week if time permits.

**Comment by glencornell** [comment]
Th last two commits fixed some minor issues when compiling against the CI environment.  The Arduino AVR/UNO support introduces a little `#ifdef` ugliness into `Statistic.h`.

**Comment by RobTillaart** [comment]
@glencornell

Haven't found time yet to check your submission, you might update the version to 1.0.0 as it is a major change in the API.

- version in statistic.h   library.json    library.properties
- update the examples
- test folder (CI part)
- readme.md

If you don't have time let me know, I'll can pick up later this week (hope thursday)

**Comment by glencornell** [comment]
@RobTillaart : 
Sorry for giving you broken code in a pull request! I didn’t realize that the tool chain was different amongst various hardware platforms.  As a result, I added commit https://github.com/RobTillaart/Statistic/pull/8/commits/ac4ce1b99b8979790f45d56cf783c97032b2164a to account for tool chains without the standard c++ library.  
clearly, I missed something and will have to review the error log. 
is there a way to run the CI environment on my branch before I pollute your inbox with commits that potentially fail?

**Comment by RobTillaart** [comment]
yes possible to run locally, but I don't use it locally. - https://github.com/Arduino-CI/arduino_ci
As long as you don't submit 10 x hour I don't care as I only read the last failed one.

**Comment by RobTillaart** [comment]
(I had not taken time yet to read your submissions in detail, sorry)

**Comment by glencornell** [comment]
I think I finally have a version that will pass the CI test build.  Additionally, it allows for overriding feature tests in custom platform builds.  Note that this code also has backwards compatibility with API version 0.4.4. but issues compiler warnings if deprecated API methods are used.

**Comment by RobTillaart** [comment]
Great, now find some time to review it!
well done!

**Comment by RobTillaart** [comment]
@glencornell 

ran test sketch TimingTest.ino

```
TimingTest.ino
Demo Statistics lib 0.5.0     (manual patch version number)
        Count: 10000
          Min: 1.0100
          Max: 100.9600
      Average: 50.9408
     variance: 835.0057
    pop stdev: 28.8965
 unbias stdev: 28.8979
     time(ms): 2535
=====================================
        Count: 10000
          Min: 1.0000
          Max: 100.9800
      Average: 51.4161
     time(ms): 2537        <<<<<<<<<<<<<<<<<
```

statistical values are identical compared to previous versions (👍)
timing is worse as **useStdDev** set to false in **clear(false)** has no effect anymore (runtime). 


```
TimingTest.ino
Demo Statistics lib 0.4.0
        Count: 10000
          Min: 1.0100
          Max: 100.9600
      Average: 50.9408
     variance: 835.0057
    pop stdev: 28.8965
 unbias stdev: 28.8979
     time(ms): 2537
=====================================
        Count: 10000
          Min: 1.0000
          Max: 100.9800
      Average: 51.4161
     time(ms): 1514               <<<<<<<<<<<<<<<<
```

**Comment by RobTillaart** [comment]
Compared sketch size and RAM usage for the 4 example sketches and that showed improvement in size  (RAM differs).
- 0.5.0 is the new version
- last line is the sum of sizes / Ram to get the average.

==> saves ~100 bytes on a sketch size 

UNO | 0.4.4 | 0.5.0 |   | 0.4.4 | 0.5.0 |  
-- | -- | -- | -- | -- | -- | --
sketch | size | size | delta | RAM | RAM | delta
Average | 5658 | 5558 | 98,23% | 489 | 488 | 99,80%
StatisticArray | 4928 | 4810 | 97,61% | 500 | 496 | 99,20%
statistic_add_overflow | 4392 | 4336 | 98,72% | 369 | 376 | 101,90%
TimingTest | 5538 | 5438 | 98,19% | 495 | 494 | 99,80%
  |   |   |   |   |   |  
  | 20516 | 20142 | 98,18% | 1853 | 1854 | 100,05%

**Comment by RobTillaart** [comment]
going to update meta data to prep for new release -1.0.0

**Comment by RobTillaart** [comment]
@glencornell 
I will add you to library.json file unless you do not want to.

**Pull request merged**
